name: swift

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  # Build and test on multiple platforms
  build-and-test:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        swift: ["6.0.0"]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Swift
      uses: SwiftyLab/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - name: Build
      run: swift build -c release
    - name: Run tests with Swift Testing
      run: swift test

  generate-documentation:
    name: Generate Documentation
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Swift
      uses: SwiftyLab/setup-swift@v1
      with:
        swift-version: "6.0.0"
    - name: Install swift-doc
      run: brew install swiftdocorg/formulae/swift-doc || true
    - name: Generate Documentation
      run: swift-doc generate Sources --module-name DelaunayTriangulation --format html --output docs
    - name: Upload Documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs