name: Swift Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  validate-release:
    name: Validate Release
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build & Test
        uses: vapor/swiftly-action@v0.1
        with:
          swift-version: "6.0"
          working-directory: .
          run: |
            swift --version
            swift build -c release
            swift test
      
      - name: Generate Documentation
        uses: vapor/swiftly-action@v0.1
        with:
          swift-version: "6.0"
          working-directory: .
          run: |
            # Install swift-doc
            brew install swiftdocorg/formulae/swift-doc || true
            mkdir -p Documentation
            swift-doc generate Sources --module-name DelaunayTriangulation --format html --output Documentation