name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            swift: "6.0"
          - os: ubuntu-latest
            swift: "6.0"
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Swift
        uses: vapor/swiftly-action@v0.1
        with:
          toolchain: ${{ matrix.swift }}
      
      - name: Show Swift version
        run: swift --version
      
      - name: Build
        run: swift build -v
      
      - name: Run tests
        run: swift test -v